CREATE TABLE CLIENTES (
    CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    CIDADE VARCHAR(40) NOT NULL,
    UF CHAR(2) NOT NULL
);

CREATE TABLE PRODUTOS (
    CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(300) NOT NULL,
    PRECO_VENDA DECIMAL(13, 2) NOT NULL
);

CREATE TABLE PEDIDOS (
    NUMERO_PEDIDO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATA_EMISSAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CODIGO_CLIENTE INT NOT NULL,
    VALOR_TOTAL DECIMAL(13, 2) NOT NULL,
    FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
	INDEX IDX_CODIGO_CLIENTE (CODIGO_CLIENTE),
    INDEX IDX_DATA_EMISSAO (DATA_EMISSAO)
);

CREATE TABLE PEDIDOITENS (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NUMERO_PEDIDO INT NOT NULL,
    CODIGO_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,    
    VALOR_UNITARIO DECIMAL(13, 2) NOT NULL,
    VALOR_TOTAL DECIMAL(13, 2) NOT NULL,
    FOREIGN KEY (NUMERO_PEDIDO) REFERENCES PEDIDOS(NUMERO_PEDIDO)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
	FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTOS(CODIGO)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
	INDEX IDX_NUMERO_PEDIDO (NUMERO_PEDIDO),
    INDEX IDX_CODIGO_PRODUTO (CODIGO_PRODUTO)
);